// Generated by CoffeeScript 2.5.1
(function() {
  module.exports = {
    opinions: {
      like: true,
      meh: true,
      bleh: true,
      hate: true
    },
    goodOpinions: { // don't skip these
      like: true,
      meh: true
    },
    opinionOrder: [
      'like',
      'meh',
      'bleh',
      'hate' // always in this specific order
    ],
    tags: {
      nsfw: "NSFW",
      bass: "Bass",
      dance: "Dance",
      bet: "BET",
      cmt: "CMT",
      vh1: "VH1",
      "70s": "70s",
      "80s": "80s",
      disco: "Disco",
      soultrain: "SoulTrain"
    }
  };

}).call(this);
