// Generated by CoffeeScript 2.5.1
(function() {
  module.exports = {
    opinions: {
      like: true,
      meh: true,
      bleh: true,
      hate: true
    },
    goodOpinions: { // don't skip these
      like: true,
      meh: true
    },
    opinionOrder: [
      'like',
      'meh',
      'bleh',
      'hate' // always in this specific order
    ]
  };

}).call(this);
